name: CI

on: [push, pull_request]

env:
  GO11MODULE: on

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.13'

    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Clean up extra files
      run: rm ./_testcases/*.go

    - name: Download deps
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      env:
        GOROOT: ''
      with:
        version: 'v1.49.0'

    - name: Run tests
      run: go test -race -v ./...

    - name: Submit coverage report
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go test -covermode=count -coverprofile=profile.cov
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github

